apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-1
spec:
  serviceName: mongo-1
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage-1
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
      volumes:
      - name: mongo-persistent-storage-1
        persistentVolumeClaim:
          claimName: mongo-persistent-storage-1
          storage: 1Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-2
spec:
  serviceName: mongo-2
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage-2
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
      volumes:
      - name: mongo-persistent-storage-2
        persistentVolumeClaim:
          claimName: mongo-persistent-storage-2
          storage: 1Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-3
spec:
  serviceName: mongo-3
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage-3
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
      volumes:
      - name: mongo-persistent-storage-3
        persistentVolumeClaim:
          claimName: mongo-persistent-storage-3
          storage: 1Gi
